-- ============================================
-- EduTrackX — Database Setup
-- Student Result Management System
-- ============================================
-- Run this file in MySQL to create the database,
-- tables, and seed data.
--
-- Usage:
--   mysql -u root -p < database.sql
-- ============================================

-- Create the database
CREATE DATABASE IF NOT EXISTS edutrackx
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE edutrackx;

-- ============================================
-- Table: admin
-- Stores admin login credentials
-- ============================================
CREATE TABLE IF NOT EXISTS admin (
    id          INT AUTO_INCREMENT PRIMARY KEY,
    username    VARCHAR(50)  NOT NULL UNIQUE,
    password    VARCHAR(255) NOT NULL,  -- Stores werkzeug hashed password
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- ============================================
-- Table: students
-- Stores student information
-- ============================================
CREATE TABLE IF NOT EXISTS students (
    id          INT AUTO_INCREMENT PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    roll_no     VARCHAR(30)  NOT NULL UNIQUE,
    class       VARCHAR(50)  NOT NULL,
    password    VARCHAR(255) NOT NULL,
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    INDEX idx_roll_no (roll_no)
) ENGINE=InnoDB;

-- ============================================
-- Table: marks
-- Stores subject-wise marks for each student
-- ============================================
CREATE TABLE IF NOT EXISTS marks (
    id          INT AUTO_INCREMENT PRIMARY KEY,
    student_id  INT          NOT NULL,
    subject     VARCHAR(100) NOT NULL,
    marks       INT          NOT NULL CHECK (marks >= 0 AND marks <= 100),
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE,
    UNIQUE KEY unique_student_subject (student_id, subject)
) ENGINE=InnoDB;

-- ============================================
-- Seed Data: Default Admin Account
-- Username: admin
-- Password: admin123 (hashed with werkzeug)
-- ============================================
-- The hash below is generated by:
--   from werkzeug.security import generate_password_hash
--   generate_password_hash('admin123')
-- We'll insert it via the app's init script instead,
-- so this is a fallback with a placeholder.
-- The app.py will auto-create the admin on first run.

-- ============================================
-- Sample Data (Optional - for testing)
-- ============================================
-- Uncomment the lines below to add sample students and marks

-- INSERT INTO students (name, roll_no, class) VALUES
--     ('Rahul Sharma', 'STU001', 'CS-A'),
--     ('Priya Patel', 'STU002', 'CS-B'),
--     ('Amit Kumar', 'STU003', 'IT-A');

-- INSERT INTO marks (student_id, subject, marks) VALUES
--     (1, 'Mathematics', 92),
--     (1, 'Physics', 85),
--     (1, 'Chemistry', 78),
--     (1, 'English', 88),
--     (1, 'Computer Science', 95),
--     (2, 'Mathematics', 76),
--     (2, 'Physics', 82),
--     (2, 'Chemistry', 65),
--     (2, 'English', 90),
--     (2, 'Computer Science', 88);
